services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    network_mode: host
    environment:
      - MONGO_URI=mongodb://localhost:27017/
    volumes:
      - ${PWD}/config.ini:/app/config.ini
      - /path/to/ssh/key:/app/key
    depends_on:
      - mongodb
